### ISSUE TITLE
Add Visual Studio 2017 build to AppVeyor

### ISSUE THREAD

**Issue by mloskot** [nanodbc/nanodbc#130]
_From @mloskot on March 19, 2017 11:41_

Currently, we CI build only w/ VS2015. We need to start building with VS2017 too. We consider both VS versions supported.

## Solution
Looks like AppVeyor offers VS2017 images (see https://github.com/appveyor/ci/issues/1179#issuecomment-286696616)

```
environment:
  matrix:
  - platform: x64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  - platform: x64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
```

_Copied from original issue: lexicalunit/nanodbc#247_
